### ISSUE TITLE
System.NotImplmentedException using FileStreamingTarget in universal Windows Phone 8.1 app

### ISSUE THREAD

**Issue by CuriousCurmudgeon** [onovotny/MetroLog#53]
I am seeing the below exception when attempting to use the FileStreamingTarget in a universal Windows Phone 8.1 app.

I think the issue is that the NuGet package does not have the right version of MetroLog.Platform. The source code shows that you are aware of this issue and uses a conditional compilation statement for WINDOWS_PHONE_APP to work around it. However, if I decompile the version of MetroLog.Platform distributed for Wpa81 apps, I see that WINDOWS_PHONE_APP was not defined and QueryOptions is called.

```
System.NotImplementedException: The method or operation is not implemented.
   at Windows.Storage.Search.QueryOptions..ctor(CommonFileQuery query, IEnumerable`1 fileTypeFilter)
   at MetroLog.WinRTFileTarget.<DoCleanup>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MetroLog.Targets.FileTargetBase.<CheckCleanupAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MetroLog.Targets.FileTargetBase.<WriteAsyncCore>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at MetroLog.Targets.Target.<WriteAsync>d__0.MoveNext()
```

**Comment by onovotny** [comment]
Closing for now as the next release will have everything in "bait-and-switch" PCL's; this shouldn't be an issue then.
